import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main></main>
    </>
  )
}
