import Head from 'next/head'

import inctagramIcon from '/public/inctagram.png'

type Props = {
  description?: string
  favicon?: string
  title?: string
}

export default function HeadMeta({
  description = 'Generated by create next app',
  favicon,
  title = 'Next App',
}: Props) {
  return (
    <Head>
      <title>{title}</title>
      <meta content={description} name={'description'} />
      <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
      <link href={favicon || inctagramIcon.src} rel={'icon'} />
    </Head>
  )
}
